### ISSUE TITLE
[Feature Request] Add offline support

### ISSUE THREAD

**Issue by duzda** [duzda/deezer-enhanced#17]
How to implement this windows' version feature?

**Comment by duzda** [comment]
This could be accomplished by replacing the current code base (app.js, window.js) and replace these with Window's app version that gets injected.

**Comment by lm41** [comment]
Is there anything new on this topic? I would love to have Offline support.

**Comment by duzda** [comment]
Sorry, you're definitely not the only one who would love to have this feature, but this is something I still haven't been able to figure out reasonably.

I've dropped the original idea and instead I'm thinking of somehow integrating whatever magic deemix does.

**Comment by lm41** [comment]
Yes, deemix would be also an option. The unofficial [deezer client](https://aur.archlinux.org/packages/deezer) from the aur has this feature. I don't know how much effort it is to copy the download function from that, but maybe you should try it, or is that what you meant in the first comment.

**Comment by duzda** [comment]
I know that the Deezer package from aur contains this feature, however it's the official Deezer application just rebuilt for linux. There are a few problems with that. Firstly, it requires a lot of disassembling and I'm not doing that, it's pain in the  ... Secondly, afaik Deezer has DRM protection over the files, which makes it unusable in any other application. Lastly on Windows it's impossible to change the downloads location, which is problematic, if you download the application onto SSD, but want all the music on HDD.

**Comment by duzda** [comment]
In other words, yes this is what I've meant by the first comment, but also that's the reason why I think copying the functionality over would suck.

**Comment by lm41** [comment]
Thanks, it's all a little clearer now. I think there is a JS library for deemix, but I don't know how it works or how to implement it. I have absolutely zero JS experience, so I can't estimate how much time and effort it would take to implement it.

**Comment by duzda** [comment]
This issue consists of 3 steps.

1. Let user download files (this is somewhat implemented as of now)
2. Allow the offline usage of the app
3. Play the local files
