### ISSUE TITLE
[Feature Request] Set output device

### ISSUE THREAD

**Issue by lm41** [duzda/deezer-enhanced#31]
It would be pretty awesome, if deezer-enhanced would provide the posibility to select the output device. I have the GoXLR, which has 5 Output channels and everytime the audio starts again I have to go to pavoucontrol and select the music channel. (Default is System).

**Comment by duzda** [comment]
I see, sounds great, I'll look into it!

**Comment by duzda** [comment]
This issue is probably upstream.

https://github.com/electron/electron/issues/27581
https://github.com/electron/electron/issues/7470

**Comment by lm41** [comment]
I'm closing this because the error never occurred again. I don't know what it was, but it seems to be gone now.
