### ISSUE TITLE
[BUG]: Getting Error "ERR_CONNECTION_REFUSED, Error ID: -102" after upgrading to v.0.3.0

### ISSUE THREAD

**Issue by lm41** [duzda/deezer-enhanced#34]
I installed deezer-enhanced from the AUR and deleted `~/.config/deezer-enhanced`. Now I'm getting this error everytime I start the application. 
![Screenshot from 2022-08-02 11-31-12](https://user-images.githubusercontent.com/59062169/182344219-951749ff-5494-4f32-a109-b167afb95955.png)
Closing the Error closes the Application.

**Comment by duzda** [comment]
Hello, are you using the package named deezer-enhanced-git, deezer-enhanced-bin or just deezer-enhanced from aur? If deezer-enhanced, then instead of deleting `~/.config/deezer-enhanced` you have to delete `~/.config/Deezer Enhanced`

**Comment by lm41** [comment]
Never mind. Now it works, although I have not changed anything.
