### ISSUE TITLE
The app window stays empty when it gets back focus when Optimize application is turned on

### ISSUE THREAD

**Issue by gree7** [duzda/deezer-enhanced#39]
The app window gets empty (only logo stays) if it loses focus and regains it back when the "Optimize application" option is turned on.

https://user-images.githubusercontent.com/997305/191211431-46ab255d-78c2-4426-a972-2aec3bf15577.mp4

Operating System: EndeavourOS
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.8-zen1-1-zen (64-bit)
Graphics Platform: X11
pacman -Q electron
electron 20.0.3-2
pacman -Q electron17
electron17 17.4.11-2
pacman -Q electron19
electron19 19.0.13-2

**Comment by gree7** [comment]
A workaround (working even with closing into the tray) at least in KDE: set "focus stealing prevention" to "force" and "Extreme" in the Special Window Settings.

**Comment by gree7** [comment]
Aha ... or turn off in the app: 
Optimize application: Optimizes application when it's not focused
(stupid me :])

**Comment by gree7** [comment]
But still... I would expect either, the app is "loaded back" when it gets the focus back, or at least there is an explanation text next to the "Optimize application" option.

**Comment by duzda** [comment]
Hello!

You're absolutly right with your latest comment, the app should "load back" when it regains focus, this a bug, thanks a lot for reporting!

**Comment by gree7** [comment]
Cool. Thanks a lot for the fix.
