### ISSUE TITLE
[Feature Request] Discord rich presence implementation

### ISSUE THREAD

**Issue by LTE-creator** [duzda/deezer-enhanced#40]
Hey! 
I don't think that this will be too hard to do because someone actually already did it: deezerRPC (https://github.com/Braasileiro/DeezerRPC) does just that and since it's open source and already available on Linux maybe can be done without to much effort?
Hope you're doing well and thank you for this amazing project!

**Comment by duzda** [comment]
Hello, sounds great to me, I'll look into it! Considered it myself, just wasn't sure whether this feature is something anyone would appreciate, so thanks for letting me know. Also, thank you for your kind words, this always makes me smile! :)

**Comment by duzda** [comment]
![image](https://user-images.githubusercontent.com/25201406/194934747-746ffa07-fcaa-41ea-b64b-7925b6ab546a.png)
Kinda happy with the result, way easier than I expected! :smiley:
