### ISSUE TITLE
Support Discord Rich Presence

### ISSUE THREAD

**Issue by Grooty12** [duzda/deezer-enhanced#41]
The Deezer app doesn't have this either, so it would make sense to add it here. 
Like the [DeezerRPC project](https://github.com/Braasileiro/DeezerRPC)

**Comment by duzda** [comment]
Hello, I've added it, but you have to use git version as of right now. I think I should push an update for binaries as well! :smile:

**Comment by Grooty12** [comment]
Didn't know that, thank you. Gonna use that instead lol
