### ISSUE TITLE
Triple notification on KDE Plasma when track switches

### ISSUE THREAD

**Issue by TheTimeWalker** [duzda/deezer-enhanced#43]
Since v0.3.0 there seems to be a bug with the notifications where at any point the player goes to the next track, I get triple notifications.

![image](https://user-images.githubusercontent.com/8660693/203758612-851db677-e3be-4ad5-8320-8ecda25843e7.png)

What happens is that the bottom notification is the new song that plays without the artwork. It then sends the middle notification with the former song and the artwork but still keeping the new artist name (Warteflame instead of Black Box) . The latest notification on top is the new song again but with the correct artwork and title.

Running on Arch with Plasma 5.26.3. I installed deezer-enhanced-bin from the AUR

**Comment by duzda** [comment]
Hello!

Sorry had no luck reproducing this issue, so feel free to add in some more details. I'm not using notifications on my computer, so just did a quick test, the code seems to be working just fine, this however might not mean anything and I may end up trying this in VM later. Also only tested daily mixes and albums.

**Comment by duzda** [comment]
So, just tested this on the latest Manjaro, still had no luck replicating.

**Comment by slash-r** [comment]
I just installed deezer-enhanced on kubuntu 22.10 and am experiencing the same issue.

**Comment by duzda** [comment]
So apparently, it's strange that the cover arts ever worked as I'm using an undocumented API but I have no clue why I can't make them work even on older versions? I remember pretty well testing and seeing cover arts in notifications, now I can't see them on any version of deezer-enhanced on either KDE and XFCE.

Spent a few days with this issue, still don't have much clue. When run without notifications service, there seems to be 3 warnings for each notification, which might be the cause of this? Nevertheless I don't really know what these warnings try to do. 
![image](https://user-images.githubusercontent.com/25201406/213920197-bea5f0df-2486-44ae-ad60-cd7bdfbc77ba.png)

Fixed a few other bugs regarding notifications, so feel free to test the git version, however I highly doubt i fixed this specific issue. Feel free to let me know about any other projects built with electron that use notifications!

**Comment by duzda** [comment]
Rewrite no longer supports notifications, if that's something you'd like to see, please create a new issue.
