### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by duzda** [duzda/deezer-enhanced#49]
Deezer's UI got updated, so there are a few changes that need to be made for everything to be working properly once again.

**Comment by lm41** [comment]
![image](https://github.com/duzda/deezer-enhanced/assets/59062169/722769c6-972a-45f9-934f-df91e94d9b0c)
The advanced settings can't be changed anymore.

**Comment by lm41** [comment]
Are there any news on this issue?

**Comment by duzda** [comment]
Yup! Finally got a little bit of spare time, so I'm rewriting the app, that will fix all these issues once for all. I can't promise you, when will the release be available, but hopefully I should be able to push a testing version in a month.

**Comment by lm41** [comment]
Nice, thank you. Keep up the good work.

**Comment by duzda** [comment]
Rewrite has completely differently laid out UI to avoid these kinds of issues in the future.
