### ISSUE TITLE
Impossible to access to the enhanced setting of the app

### ISSUE THREAD

**Issue by C3PO987** [duzda/deezer-enhanced#51]
Hi,
Everything works well but... when I clic on the icon to access to the enhanced settings, nothing happen :/
Any Idea ?

thx a lot by the way for your awesome work

**Comment by duzda** [comment]
Hello!

Already mentioned [here](https://github.com/duzda/deezer-enhanced/issues/49) and [here](https://github.com/duzda/deezer-enhanced/issues/50), therefore closing. New update solving this and many other issues is on the way, although still a little bit far away!

**Comment by C3PO987** [comment]
So sorry, I didn't see these post !
Goodluck and keepgoing, you rock !
